version: "3"

services:
  chat:
    image: chat
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    restart: unless-stopped
    container_name: chat
    command: python3 main.py
    env_file: .env
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
  postgres:
    image: postgres:15.0
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: postgres
    ports:
      - "8001:5432"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine3.17
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data: {}
