version: "3"

services:
  chat:
    image: chat
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    restart: unless-stopped
    container_name: chat
    command: python3 main.py
    env_file: .env
    environment:
      ENV: ${ENV}
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/workspace
