name: development build and push docker image to ghcr.io

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/chat_server

jobs:
  build-and-push:
    name: build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Extract metadata (tag, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Auth
          push: true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}dev
          flavor: |
            latest=true
          labels: ${{ steps.meta.outputs.labels }}
